services:
  - type: web
    name: sih-evidence-locker
    env: python
    region: singapore
    buildCommand: "bash render-build.sh"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: POLYGON_CONTRACT_ADDRESS
        value: 0xA94D3FF15B2c24E8e2E820d6e631c79a69b2b14c
      - key: POLYGON_RPC_URL
        value: https://polygon-amoy-bor-rpc.publicnode.com
      - key: POLYGON_WALLET_ADDRESS
        value: 0xc58dC13162fcA1b04AF4af2Ea9072d8FDE1ef8f7
      - key: GEMINI_API_KEY
        sync: false
      - key: POLYGON_PRIVATE_KEY
        sync: false
